version: "3.8"
services:
 frontend:
   build: ./frontend
   ports:
   - target: 5000
     published: 5000 
 backend:
   build: ./backend
   ports:
   - target: 5001
     published: 5001
   environment:
    SECRET_KEY: $SECRET_KEY
    DATABASE_URI: $DATABASE_URI
 database:
   build: ./database
   ports:
   - target: 3306 
     published: 3306 
   environment:
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
   
 

