version: "3.8"
services:
 frontend:
   build: ./frontend
   ports:
   - target: 5000
     published: 5000 
 backend:
   build: ./backend
   ports:
   - target: 5001
     published: 5001
   environment:
   - SECRET_KEY=password
   - DATABASE_URI=mysql+pymysql://root:password@database:3306/users
 database:
   build: ./database
   ports:
   - target: 3306 
     published: 3306 
   environment:
   - MYSQL_ROOT_PASSWORD=password

 nginx:
   image: nginx:alpine
   ports:
   - "80:80"
   volumes:
   - type: bind
     source: ./Nginx/nginx.conf
     target: /etc/nginx/nginx.conf
   depends_on:
    - frontend   
 

