apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: frontend
        image: jullfiqur/sfia2:frontend 
        ports:
        - containerPort: 5000
      - name: backend
        image: jullfiqur/sfia2:backend
        ports:
        - containerPort: 5001
      - name: database
        image: jullfiqur/sfia2:database
        ports:
        - containerPort: 3306

        
