apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas:
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
