--- 
- hosts: all
  become: true
  tasks:
  - name: install docker-compose
    script: dockercomposeinstall.sh
  - name: install docker
    script: installdocker.sh
  - name: install jenkins'
    script: installjenkins.sh
  - name: install kubectl
    script: installkubectl.sh


 
