- hosts: all
  tasks:   
  - name: 'Install Jenkins'
    apt:
      name: jenkins
      state: latest
      update_cache: true
  - name: 'Start NGINX Service'
    service:
      name: nginx
      state: started

